### ISSUE TITLE
[bug] Laravel SQS worker sending empty messages continously

### ISSUE THREAD

**Issue by cristiancmello** [shiftonelabs/laravel-sqs-fifo-queue#2]
Laravel keeps sending empty messages continuously.
Even bug reported in: [laravel-heroku-sqs-worker-sending-empty-messages-continously-error-on-countable](https://stackoverflow.com/questions/49160800/laravel-heroku-sqs-worker-sending-empty-messages-continously-error-on-countable)

OS: Linux Mint Sylvia
Framework: Laravel 5.6.7

**Comment by patrickcarlohickman** [comment]
Are you still having this issue? I answered that SO question. It was due to the OP using Laravel < 5.5.25 with PHP 7.2. However, you mentioned you were are 5.6.7, which should not be having that issue.

If you are still having this issue, does it occur with Laravel's built in SQS queue driver for non-FIFO queues?

Any error messages?
