### ISSUE TITLE
Cannot use integer as messageGroupId anymore

### ISSUE THREAD

**Issue by bruno-rodrigues** [shiftonelabs/laravel-sqs-fifo-queue#28]
After upgrading from Laravel 8 to Laravel 9 we upgraded to your latest version but now all the places where we used an integer as messageGroupId are failing.

```
In QueryCompatibleInputMiddleware.php line 165:

  The provided type for `MessageGroupId` value was `integer`. The modeled type is `string`.
```

Should public function onMessageGroup($messageGroupId) only accept strings (or cast inputs into string)?

Thank you

**Comment by patrickcarlohickman** [comment]
@bruno-rodrigues ,

This was due to a change in the AWS SDK. AWS added the type checking in version 3.285.0. When you upgraded your version, it must have upgraded the SDK version being used.

While I'm sure you've since resolved the issue on your end, I have just released a patch update that will prevent the error. The `MessageGroupId` and `MessageDeduplicationId` will now be passed through `strval()` before being sent to AWS.

Thanks,
Patrick
