### ISSUE TITLE
sqs-fifo with jobs and delays

### ISSUE THREAD

**Issue by alexkb** [shiftonelabs/laravel-sqs-fifo-queue#3]
I'm not sure if this is a question specific to your Laravel implementation (great work btw) or whether its a SQS FIFO specific thing, but if I create a job with a delay as per the Laravel docs:

    ProcessPodcast::dispatch($podcast)
        ->delay(now()->addMinutes(10));

Does that means other jobs (without a delay) sent to the queue will be processed before this one, even though they arrived after? 

I guess the question could be rephrased to: can I control the order of FIFO items, by setting the delay?

**Comment by patrickcarlohickman** [comment]
With SQS FIFO queues, the delay isn't controlled by the job; it is controlled by the queue definition in SQS. [From the package docs:](https://github.com/shiftonelabs/laravel-sqs-fifo-queue#delayed-jobs)

>SQS FIFO queues do not support per-message delays, only per-queue delays. The desired delay is defined on the queue itself when the queue is setup in the Amazon Console. Attempting to set a delay on a job sent to a FIFO queue will have no affect. To this end, using the `later()` method to push a job to an SQS FIFO queue will generate a `BadMethodCallException`.
>
>To delay a job, you must `push()` the job to an SQS FIFO queue that has been defined with a delivery delay.

So, no, you can't control the execution order. They take very seriously the idea that it is a FIFO queue. Now, you could setup some application level logic that your jobs use so that they re-queue themselves if they're not supposed to run yet, but if you're doing that, then you probably don't need to be using SQS FIFO queues, and can just use regular SQS queues.

Depending on your needs, you may also consider using [message groups](https://github.com/shiftonelabs/laravel-sqs-fifo-queue#message-groups). The queues are FIFO per message group, and the message groups are completely independent of each other. So if you dispatch jobs 1 and 3 to message group A, and 2, 4, and 5 to message group B, then 1 will always run before 3, and 2 will always run before 4 and 5, but the order of the groups is indeterminate. For example, you could end up running 2(B), 1(A), 4(B), 5(B), 3(A).

**Comment by alexkb** [comment]
@patrickcarlohickman - great, thanks a lot for the explanation. We went ahead and switched to standard SQS. Cheers.
