### ISSUE TITLE
Upgrade to Laravel Version 11

### ISSUE THREAD

**Issue by MattWiseParking** [shiftonelabs/laravel-sqs-fifo-queue#31]
Will anybody be uprading this package to laravel version 11?

**Comment by patrickcarlohickman** [comment]
@MattWiseParking ,

Because there aren't too many changes to the queuing functionality, the package has open-ended dependencies so that you can use the package on the newest versions without having to wait for the package to be updated. It will most likely work.

That said, I have updated the package to test against Laravel 11 and PHP 8.3, and everything still looks good. I have updated the readme to reflect the newly tested version.

Thanks,
Patrick
