### ISSUE TITLE
PHP worker fails to run queue items in laravel 4.2

### ISSUE THREAD

**Issue by bnagydeveloper** [shiftonelabs/laravel-sqs-fifo-queue#7]
Hi, I'm trying to integrate this packege with laravel 4.2. The problem I'm having is that laravel 4.2 stores the jobs class under the "job" key and from that a new instance is created and so on.

In my case I need different message groups for each job, so I am giving an instance of the job to the queue and setting $messageGroupId for it, but doing so under the "job" the name of the class in not sent.

Expected message sent to sqs fifo
`{"job":"App\\Models\\Jobs\\AJob","data":[],"group":"group-1"}`
Actual message is sent to sqs fifo
`{"job":{"messageGroupId":"events-1","deduplicator":null},"data":[],"group":"group-1"}`

**Comment by patrickcarlohickman** [comment]
I looked into the issue, and unfortunately, it looks like Laravel didn't support passing job instances to the queue until 5.0. Laravel 4.1 and 4.2 only support passing in class names or closures.

A workaround attempting to use closures won't work, though, since it won't have the message group information on it.

This package could be updated to support passing in a job instance for 4.1 and 4.2 for the sole purpose of setting the message group, but it would need to be converted to either a plain class name or closure workaround in order to work inside the built in 4.1/4.2 queuing system.

**Comment by bnagydeveloper** [comment]
Hi, @patrickcarlohickman, that's what I was also thinking. I'll probably will fork it and make some changes to "support" 4.2. Thanks for your answer :)

**Comment by patrickcarlohickman** [comment]
@bnagydeveloper I tagged a new release (1.1.2) that should resolve this issue. As I mentioned in my original comment, you can pass in the job instance in order to set the message group, but the job instance will get converted to just the class name when it is sent to the queue for Laravel 4.1/4.2.

I assume you've already come up with some workaround, but in case you still needed it, it should be working now.

Thank you for reporting the issue.

Thanks,
Patrick
